### ISSUE TITLE
Missing rel="external" on local resources links 

### ISSUE THREAD

**Issue by neilmispelaar** [DTS-STN/Life-Journeys#102]
### Description 

There are two links on the page under the "Connect to local resources" section that point to an external domain (google.ca).

Both of these links require the `rel="external"` attributes. 

### Why do we have to do this

The [Standard of Web Interoperability Appendix D: Mark-up language requirements](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=25875) requires that appropriate `rel` attributes be applied to the page.

<img width="791" alt="Screen Shot 2021-08-08 at 9 11 04 PM" src="https://user-images.githubusercontent.com/9325038/128651749-e883d0be-cbc9-4a2b-8431-6bbcf1be6608.png">

### rel="external"

The definition of`rel="external"` attribute:

<img width="791" alt="Screen Shot 2021-08-08 at 9 09 19 PM" src="https://user-images.githubusercontent.com/9325038/128651668-f852c46f-0b4e-47f6-b084-de507fff1c62.png">

### How to test

1. Go to the project page
2. View source
3. Find the section with the heading "Connect to local resources" 
4. Check the `rel` attribute values for the two links in the section 
5. Both links are missing the `external` attributes

<img width="1634" alt="Screen Shot 2021-08-08 at 9 04 53 PM" src="https://user-images.githubusercontent.com/9325038/128651543-becf4581-4e59-466e-8e2c-1b139476773c.png">

### References 

[Standard on Web Interoperability](https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=25875)
[Rel attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel)

**Comment by P0NDER0SA** [comment]
Fixed!  thanks!
